In [2]:
import numpy as np

In [8]:
# Numpy getting started 
arr = np.array([1,2,3,4,5])
print (np.__version__)
print (arr)
print (type(arr))

1.22.0
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# 1D array
arr =np.array([42])
print (arr)
# printing the dimention 
print (arr.ndim)

[42]
1


In [12]:
# 2D array with Numpy
arr = np.array([[1,2,3],[1,4,5]])
print (arr)

[[1 2 3]
 [1 4 5]]


In [14]:
# minimum dimention 
arr = np.array([1,2,3,5], ndmin =2)
print (arr)

[[1 2 3 5]]


In [16]:
# dtype (datatype ) of numpy
arr= np.array([1,2,3,4,5], dtype = complex)
print (arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [17]:
# shape of the array 
arr = np.array([[1,2,3], [4,5,6]])
print (arr)
print (arr.shape)   

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
# Re-Arranging the shape of the numpy array 
arr = np.array([[1,2,3], [1,5,6]])
print (arr)
print (arr.shape)
arr.shape = (3,2)
print (arr.shape)

[[1 2 3]
 [1 5 6]]
(2, 3)
(3, 2)


In [8]:
# Re shapping the Numpy array
arr = np.array([[1,4,7], [2,5,8]])
print (arr)
arr = arr.reshape(3,2)
print(arr)

[[1 4 7]
 [2 5 8]]
[[1 4]
 [7 2]
 [5 8]]


In [14]:
# 3D array  (It's simply combination of the two dimention array )
arr =np.array([[[1,2,3], [4,5,6]], [[4,5,6], [7,4,8]]])
print (arr)
print (arr.shape)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 4 8]]]
(2, 2, 3)
3


In [19]:
# Array Indexing and operation 

In [21]:
# 1. Array indexing
arr = np.array([1,2,3,4,5,7,10])
print (arr[0])
print (arr[2]+ arr[4])
print (arr[: 3])

1
8
[1 2 3]


In [25]:
# 2.Accesing the 2D array elements 
arr = np.array([[1,4,7,2], [4,2,5,3]])
print ("1st Raw 3rd Elemnts is: ", arr[0,3])
print ("2nd Raw, 2nd Element is: ", arr[1,2])

1st Raw 3rd Elemnts is:  2
2nd Raw, 2nd Element is:  5


In [33]:
# 3. Accessing the Elements from the 3D array 
arr = np.array([ [[1,2,4], [4,1,7]], [[7,4,8], [5,8,6]]])
print ("Array items: ", arr)
print ("Array type: ", arr.ndim)
print ("2nd block, 1st raw 2nd Elemets: ",  (arr[1, 1, 2]))

Array items:  [[[1 2 4]
  [4 1 7]]

 [[7 4 8]
  [5 8 6]]]
Array type:  3
2nd block, 1st raw 2nd Elemets:  6


In [37]:
# 4. printing the last element
arr =np.array([[1,2,3, 5], [4,7,8,2]])
print (arr)
print (arr.ndim)
print ("2nd Raw, last elemnt: ", arr[1,-1])

[[1 2 3 5]
 [4 7 8 2]]
2
2nd Raw, last elemnt:  2


In [38]:
# Array slicing 

In [42]:
# 1. Array slicing basic 
arr = np.array([1,2,3,4,5,6,7,8,9])
print (arr)
print (arr[1:5])
print (arr[:5])
print (arr[3:])
print (arr[1:-1])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[1 2 3 4 5]
[4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [54]:
# 2. Array index slicing from 2D array
arr = np.array([[1,2,3,4,5,6], [1,4,7,2,8,6]])
print (arr)
print (arr [0:3, 2:4])

[[1 2 3 4 5 6]
 [1 4 7 2 8 6]]
[[3 4]
 [7 2]]


In [58]:
# 3. printing every other elements from the array 
arr = np.array([1,2,3,4,5,6,7,8,9])
print (arr)
print (arr[::2])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [62]:
# 4. 2D arary slicing 
arr =np.array([[1,2,3,4, 8], [1,4,5,7, 5]])
print (arr)
print (arr[1, 1:3])

[[1 2 3 4 8]
 [1 4 5 7 5]]
[4 5]


In [68]:
# 5. 2D array slicing 
arr = np.array([[1,2,3,4,5], [1,4,2,5,6]])
print (arr)
print (arr[1, 1:3])

[[1 2 3 4 5]
 [1 4 2 5 6]]
[4 2]


In [69]:
# Numpy DataTypes 
#strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
#integer - used to represent integer numbers. e.g. -1, -2, -3
#float - used to represent real numbers. e.g. 1.2, 42.42
#boolean - used to represent True or False.
#complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [70]:
# 1. Numpy datatype display
arr= np.array([1,2,3,4,5,6])
print (arr.dtype)

int64


In [71]:
#2. Numpy Datatype display
arr = np.array(["Apple", "Orange", "Cherry", "Lichi"])
print (arr.dtype)

<U6


In [74]:
# 3. Numpy datatype conversion
arr = np.array([1,2,3,4], dtype = "S")
print (arr)

[b'1' b'2' b'3' b'4']


In [75]:
# 4. Numpy Datatype conversion
arr= np.array(['1', '2', '3'], dtype ='i')
print (arr)

[1 2 3]


In [78]:
# 5. astype() methord for the Datatype conversion
arr = np.array([1.1,1.2,1.4,1.0])
int_type = arr.astype('i')   # float to int conversion 
print (int_type.dtype)

int32


In [80]:
# 6. astype() int ot bool conversion 
arr= np.array([1,2,0,1,0,3])
arr_bool = arr.astype('bool')
print (arr_bool)
print (arr_bool.dtype)

[ True  True False  True False  True]
bool


In [81]:
#NumPy Array Copy vs View
#The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [84]:
# 1. Copy the array 
arr = np.array([1,2,3,4,5,6])
dummy = arr.copy()
arr[0]= 2
print (arr)
print (dummy)

[2 2 3 4 5 6]
[1 2 3 4 5 6]


In [87]:
# 2. view the Numpy array 
arr= np.array([1,2,3,4,5,6])
print (arr)
dummy = arr.view()
arr[2] =0
print (arr)
print (dummy)

[1 2 3 4 5 6]
[1 2 0 4 5 6]
[1 2 0 4 5 6]


In [89]:
# 3. base attributes to check wheather the array is owned or not 
arr =np.array([1,2,3,4,5,6])
x= arr.copy()
y= arr.view()
print (x.base)
print (y.base)

None
[1 2 3 4 5 6]


In [90]:
# Numpy array Share and reshape

In [91]:
# 1. Numpy array shape 
arr= np.array([[1,2,3], [1,4,7]])
print (arr.shape)

(2, 3)


In [93]:
# 2. Re-shape from 1D to 2D
arr = np.array([1,2,3,4,5,6])
print (arr)
arr_reshp = arr.reshape(2,3)
print (arr_reshp)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [95]:
# 3. Array Re-Shape from 1D to 3D 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_reshp = arr.reshape(2, 2, 3)
print (arr_reshp)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [96]:
# 4. 2D array to 1D arary conversion 
arr = np.array([[1,2,3,4], [1,4,7,8]])
print (arr)
arr_reshp = arr.reshape(-1)
print (arr_reshp)

[[1 2 3 4]
 [1 4 7 8]]
[1 2 3 4 1 4 7 8]


In [97]:
# Numpy array itteration 

In [99]:
# 1. Numpy array itteration using for loop
arr = np.array([1,2,3,4,5,6])
for i in arr:
    print (i)

1
2
3
4
5
6


In [100]:
# 2.2D array itteration, element wise  
arr = np.array([[1,2,3], [1,4,7]])
for i in arr:
    print (arr)

[[1 2 3]
 [1 4 7]]
[[1 2 3]
 [1 4 7]]


In [101]:
# 3. 3D array ittegration via individual element wise 
arr = np.array([[[1,2,3], [4,5,6]], [[7,4,1], [8,5,2]]])
for i in arr:
    print (arr)

[[[1 2 3]
  [4 5 6]]

 [[7 4 1]
  [8 5 2]]]
[[[1 2 3]
  [4 5 6]]

 [[7 4 1]
  [8 5 2]]]


In [104]:
# 3D array ittergation
arr = np.array([[[1,2,3], [4,5,6]], [[7,4,1], [8,5,2]]])
for i in arr:
    for j in i:
        for k in j:
            print (k)

1
2
3
4
5
6
7
4
1
8
5
2


In [105]:
# array joining or Concating 

In [109]:
# 1. Two array concating 
x=np.array([1,2,3,4])
y=np.array([1,4,7,8])
z = np.concatenate((x,y))
print (z)

[1 2 3 4 1 4 7 8]


In [8]:
# 2. joining the 2D array at one Axies 
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,4,1],[8,5,2]])
result = np.concatenate((arr1, arr2), axis=1)
print (result)

[[1 2 3 7 4 1]
 [4 5 6 8 5 2]]


In [9]:
# spliting the array 

In [11]:
1. # Splitting the 1D array in to the 3 sub array 
arr = np.array([1,2,3,4,5,6])
arr = np.array_split(arr, 3)
print (arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
#2 Spliting the 1D array in to the group of 3
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.array_split(arr, 3)
print (arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [14]:
# Array indexing serching using where 

In [16]:
# 1. array serching using where, it will return the list of the searching result 
arr = np.array([1,4,7,1,2,1,6,1,0])
x= np.where(arr == 1)
print (x)

(array([0, 3, 5, 7]),)


In [19]:
#2. Finding the array elements at even position
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2 ==0)
print (x)

(array([1, 3, 5, 7]),)


In [21]:
# 3.Finding the array elements at odd positions 
arr= np.array([1,2,3,4,5,6,7,8])
x= np.where(arr%2 ==1)
print (x)

(array([0, 2, 4, 6]),)


In [23]:
# Sorting the array 

In [24]:
# 1. Array sorting 
arr = np.array([1,4,5,10,20,65,87,2])
x = np.sort(arr)
print (x)

[ 1  2  4  5 10 20 65 87]


In [30]:
# 2. array sorting 
arr = np.array(["Apple", "Orange", "Banana"])
x= np.sort(arr)
print (x)

['Apple' 'Banana' 'Orange']


In [33]:
# 3. array sorting
arr = np.array([True, False, True])
x= np.sort(arr)
print (x)

[False  True  True]


In [36]:
# Array filtering 
# Getting the filterd values from the array and creating the new array based on filterd values called array filtering 

In [40]:
# 1. array filtering 
arr= np.array([1,4,7,8,7])
x = [True, True, False, False, True]
print (arr[x])

[1 4 7]


In [48]:
# 2. Creating the filterd array whose value is higher than 10
arr= np.array([1,2,41,5,41,78,12,0,6,5])
filter_arr =[]
for i in arr:
    if(i > 10):
        filter_arr.append(True)
    else:
        filter_arr.append(False)
    
print (filter_arr)
print (arr[filter_arr])
        

[False, False, True, False, True, True, True, False, False, False]
[41 41 78 12]


In [52]:
# 2. Filtering the Even numbers from the list 
arr = np.array([1,4,7,8,5,2,2])
filter_arr=[]
for i in arr:
    if(i%2 ==0):
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
print (filter_arr)
print (arr[filter_arr])

[False, True, False, True, False, True, True]
[4 8 2 2]
